name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            python: python3
          - os: macos-latest
            python: python3
          - os: windows-latest
            python: python

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: ${{ matrix.config.python }} install-deps.py
      - name: Configure CMake
        run: |
          mkdir build
          cmake cpu_experiments -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -B build
      - name: Build
        run: cmake --build build

