name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: python install-deps.py
