name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            python: python3
            cxx: g++-9
            cc: gcc-9
            cmake_generator: Ninja
          - os: macos-latest
            python: python3
            cmake_generator: Ninja
          - os: windows-latest
            python: python
            cmake_generator: Visual Studio 16 2019

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: |
          sudo add-apt-repository "deb http://dk.archive.ubuntu.com/ubuntu/ xenial main"
          sudo add-apt-repository "deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe"
          sudo apt update
          sudo apt install ninja-build g++-9
        if: matrix.config.os == 'ubuntu-latest'
      - run: choco install ninja
        if: matrix.config.os == 'windows-latest'
      - run: brew install ninja
        if: matrix.config.os == 'macos-latest'
      - name: Install dependencies
        run: ${{ matrix.config.python }} install-deps.py
      - name: Setup CC and CXX
        if: runner.os == 'Linux'
        run: |
          echo "::set-env name=CC::${{ matrix.config.cc }}"
          echo "::set-env name=CXX::${{ matrix.config.cxx }}"
      - name: Setup x64
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $installationPath = $(& "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere" -latest -property installationPath)
          & "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo -arch=x64 -host_arch=x64 && set" | foreach-object {
            $name, $value = $_ -split '=', 2
            echo ::set-env name=$name::$value
          }
      - name: Configure CMake
        run: |
          mkdir build
          cmake cpu_experiments -DCMAKE_TOOLCHAIN_FILE="$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -G "${{ matrix.config.cmake_generator }}" -B build
      - name: Build
        run: cmake --build build

