name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            python: python3
          - os: macos-latest
            python: python3
          - os: windows-latest
            python: python

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: |
          sudo add-apt-repository "deb http://dk.archive.ubuntu.com/ubuntu/ xenial main"
          sudo add-apt-repository "deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe"
          sudo apt update
          sudo apt install ninja-build g++-9
        if: matrix.config.os == 'ubuntu-latest'
      - run: choco install ninja
        if: matrix.config.os == 'windows-latest'
      - run: brew install ninja
        if: matrix.config.os == 'macos-latest'
      - name: Install dependencies
        run: ${{ matrix.config.python }} install-deps.py
      - name: Configure CMake
        run: |
          mkdir build
          cmake cpu_experiments -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -B build
        shell: bash
      - name: Build
        run: cmake --build build

